//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWG.Laboratory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CommentPage
    {
        public tbl_CommentPage()
        {
            this.tbl_CommentRecord = new HashSet<tbl_CommentRecord>();
        }
    
        public long PageId { get; set; }
        public string PageName { get; set; }
    
        public virtual ICollection<tbl_CommentRecord> tbl_CommentRecord { get; set; }
    }
}
