//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWG.Laboratory.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XwgWebDBEntities : DbContext
    {
        public XwgWebDBEntities()
            : base("name=XwgWebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ChatRecord> tbl_ChatRecord { get; set; }
        public virtual DbSet<tbl_CommentPage> tbl_CommentPage { get; set; }
        public virtual DbSet<tbl_VisitRecord> tbl_VisitRecord { get; set; }
        public virtual DbSet<tbl_CommentRecord> tbl_CommentRecord { get; set; }
        public virtual DbSet<tbl_WeixinRecord> tbl_WeixinRecord { get; set; }
        public virtual DbSet<tbl_WeixinTextMessage> tbl_WeixinTextMessage { get; set; }
        public virtual DbSet<tbl_WeixinUser> tbl_WeixinUser { get; set; }
        public virtual DbSet<tbl_WeixinQa> tbl_WeixinQa { get; set; }
    }
}
